"""empty message

Revision ID: 56541b2a05dd
Revises: 951463047296
Create Date: 2021-12-17 13:43:35.298034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56541b2a05dd'
down_revision = '951463047296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='state'), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('order_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_pk'], ['orders.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.alter_column('administrators', 'role',
               existing_type=postgresql.ENUM('customer', 'worker', 'admin', name='roletype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrators', 'role',
               existing_type=postgresql.ENUM('customer', 'worker', 'admin', name='roletype'),
               nullable=True)
    op.drop_table('offers')
    # ### end Alembic commands ###
